mutation CreateJobWithUser ($job_title: String, $job_location: String, $job_link: String, $company_name: String, $company_logo: String, $highlighted: Boolean, $pinned: Boolean, $user_name: String, $user_email: String, $user_password: String, $tags: [ID!]) {
  createJobAndRegisterUser(input: {
    job_title: $job_title,
    job_location: $job_location,
    job_link: $job_link,
    company_name: $company_name,
    company_logo: $company_logo,
    highlighted: $highlighted,
    pinned: $pinned,
    user: {
      create: {
        name: $user_name,
        email: $user_email,
        password: $user_password
      }
    },
    tags: {
      connect: $tags
    }
  }) {
    id
  }
}